const challenges = [
    {
      title: "Reduce Carbon Footprint",
      description: "Commit to reducing your carbon footprint by adopting sustainable practices.",
      points: 100,
      category: "Environment",
      startDate: new Date("2024-04-01"), 
      endDate: new Date("2024-04-03"),
      isActive: true,
    },
    {
      title: "Volunteer for Community Cleanup",
      description: "Join a community cleanup event and help keep your neighborhood clean.",
      points: 150,
      category: "Community Service",
      startDate: new Date("2024-04-01"), 
      endDate: new Date("2024-04-02"),
      isActive: true,
    },
    {
      title: "Healthy Eating Challenge",
      description: "Eat healthier by incorporating more fruits and vegetables into your diet.",
      points: 120,
      category: "Health & Wellness",
      startDate: new Date("2024-04-06"), 
      endDate: new Date("2024-04-08"),
      isActive: true,
    },
    {
      title: "Exercise Challenge",
      description: "Commit to regular exercise by setting fitness goals and staying active.",
      points: 200,
      category: "Fitness",
      startDate: new Date("2024-04-06"), 
      endDate: new Date("2024-04-08"),
      isActive: true,
    },
    {
      title: "Learn Something New",
      description: "Take up a new hobby or skill and commit to learning and practicing it.",
      points: 180,
      category: "Personal Development",
      startDate: new Date("2024-03-27"), 
      endDate: new Date("2024-03-28"),
      isActive: true,
    },
    {
      title: "Reduce Screen Time",
      description: "Limit your screen time and spend more time engaging in real-life activities.",
      points: 120,
      category: "Wellness",
      startDate: new Date("2024-03-15"), 
      endDate: new Date("2024-04-06"),
      isActive: true,
    },
    {
        title: "30-Day Fitness Challenge",
        description: "Complete a daily workout for 30 days.",
        points: 100,
        category: "Fitness",
        startDate: new Date("2024-03-20"), 
        endDate: new Date("2024-03-26"),
        isActive: true,
      },
      {
        title: "Healthy Eating Challenge",
        description: "Follow a healthy diet plan for a week.",
        points: 50,
        category: "Health",
        startDate: new Date("2024-02-20"), 
        endDate: new Date("2024-03-06"),
        isActive: true,
      },
      {
        title: "Meditation Challenge",
        description: "Meditate for 10 minutes every day for a month.",
        points: 80,
        category: "Mindfulness",
        startDate: new Date("2024-01-01"),
        endDate: new Date("2024-01-15"),
        isActive: true,
      },
      {
        title: "Learn a New Skill Challenge",
        description: "Learn a new skill or hobby and practice it for a week.",
        points: 70,
        category: "Personal Development",
        startDate: new Date("2024-01-20"), // Start date is January 20, 2024
        endDate: new Date("2024-02-19"),
        isActive: true,
      },
      {
        title: "Reading Challenge",
        description: "Read a book every week and write a summary.",
        points: 60,
        category: "Personal Development",
        startDate: new Date("2024-01-20"), // Start date is January 20, 2024
        endDate: new Date("2024-02-19"),
        isActive: true,
      },
      {
        title: "Volunteering Challenge",
        description: "Volunteer at a local charity for a day.",
        points: 90,
        category: "Community",
        startDate: new Date("2024-01-20"), // Start date is January 20, 2024
        endDate: new Date("2024-02-19"),
        isActive: true,
      },
  ];
  
  module.exports = challenges;
  